version: "3.3"
services:
  redis:
    network_mode: "host"
    image: redis:latest
    ports:
      - "6379:6379"

  message-server:
    network_mode: "host"
    image: project:latest
    ports:
      - "5000:5000"
